export `x` conflicts with existing import of the same name in world `w`

Caused by:
     --> tests/resolution/fail/duplicate-world-item.wac:3:12
      |
    3 |     export x: func();
      |            ^
      |
      = export `x` conflicts with existing import of the same name in world `w`