failed to resolve document

  × import `x` conflicts with existing import of the same name in world `w`
   ╭─[tests/resolution/fail/duplicate-world-import.wac:5:12]
 4 │     import x: func();
 5 │     import x: func();
   ·            ┬
   ·            ╰── conflicting name `x`
 6 │ }
   ╰────
