import name `foo` conflicts with an instance that was implicitly imported by the instantiation of `foo:bar` at tests/resolution/fail/import-conflict.wac:3:13
    --> tests/resolution/fail/import-conflict.wac:5:8
     |
   5 | import foo: func();
     |        ^-^
